#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 kanno ryutaro
# SPDX-License-Identifier: GPL-3.0-or-later
import sys


ans = 0
for line in sys.stdin:
     try:
        ans += int(line)
     except:
        ans += int(line)

print(ans)
